# 配置注意项： 在名称和后面的值之间需要至少一个空格，没有空格时会导致该项读取不到。
spring:
    profiles:
        active: test
---
server:
    port: 8080
    # 设置请求头的最大值。
    max-http-header-size: 65536
    tomcat:
        # 设置为12M，比文件上传限制稍大。
        max-http-post-size: 12582912

# 指定日志配置文件的路径。
logging:
    config: src/main/resources/logback.xml

# 指定mybatis的mapper文件路径。
mybatis:
    mapper-locations: classpath*:mybatis/**/*.xml
    configuration:
        cache-enabled: false
        lazy-loading-enabled: false

spring:
    profiles: test
    application:
        name: oklink-payboot-remit-zhujizhi
    datasource:
        # druid的各项配置
        druid:
            name: payboot
            url: jdbc:mysql://192.168.10.107:3306/superpay_test?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
            username: lekuda
            password: 123456
            driver-class-name: com.mysql.jdbc.Driver
            max-active: 8
            min-idle: 2
            initial-size: 1
            max-wait: 10000
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            validation-query: SELECT 1
            time-between-eviction-runs-millis: 30000
            min-evictable-idle-time-millis: 30000
            remove-abandoned: true
            remove-abandoned-timeout: 180
            log-abandoned: false

            filter:
                # StatFilter提供SQL监控和日志。
                stat:
                    enabled: true # 是否开启该过滤。
                    log-slow-sql: true # 是否开启慢SQL记录。
                    slow-sql-millis: 500 # 慢于500毫秒的认为是慢SQL。
                    merge-sql: false # 合并SQL，如"SELECT 1"，会拉慢部分SQL执行。
                # SQL日志输出。和logback中的druid.sql配合使用。
                slf4j:
                    enabled: true # 是否开启SQL输出
                    data-source-log-enabled: false
                    connection-log-enabled: false
                    statement-log-enabled: true
                    result-set-log-enabled: false
                    statement-create-after-log-enabled: false
                    statement-close-after-log-enabled: false

            # 状态监控页面配置。
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                allow: # 白名单
                deny: # 黑名单
                login-username: druid # 用户名
                login-password: druid123 #密码
                reset-enable: true
            # 状态监控过滤器配置。
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
                session-stat-enable: true
                session-stat-max-count: 200
                profile-enable: true


